import java.until

public class Cofrinho implements Comparable<Cofrinho>{


    List<Moeda> moedas = new ArrayList<>();

    public int compareTo(Cofrinho o){
            
    }

    public void addMoeda(Moeda m){
        moedas.add(m);
    }

    public double get ValorTotal(){
        return;
    }

    public int getQuantMoedas(){
        
    }

    public Moeda getMoedaMaiorValor(){
        return;
    }

    public void ordenaMoedas(){

    }

}